### ISSUE TITLE
Analog HUD for all camera views for Gran Turismo 4 SCUS-97436 (GT4 Online Public Beta) SCUS-97436 32A1C752

### ISSUE THREAD

**Issue by syaifulnizamyahya** [AeroWidescreen/PCSX2-Cheats#1]
Hi Aero,

Is it possible to create Analog HUD for all camera views for Gran Turismo 4 SCUS-97436 (GT4 Online Public Beta) SCUS-97436 32A1C752?

Thanks.

**Comment by AeroWidescreen** [comment]
Sorry for responding so late, I don't actively check my Github. I'll look into this very soon.

**Comment by AeroWidescreen** [comment]
Done. Additionally, I added a patch that restores the original retail behavior of the HUD when you're using the roof (hood / bonnet) camera. 

```
gametitle=Gran Turismo 4 Online Public Beta [SCUS-97436] (U)
[Analog HUD for Roof Camera]
description=Restores the default HUD behavior of retail GT4.
author=Aero_
patch=1,EE,206EC59C,extended,001C2688
```

**Comment by syaifulnizamyahya** [comment]
Thank you! Really appreciate it.
